apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lesquotesawil
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thequoter
    spec:
      containers:
      - name: lesquotesawil
        image: pastjean/thequoter:v2
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: http

---

kind: Service
apiVersion: v1
metadata:
  name: thequoter
spec:
  selector:
    app: thequoter
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: http